services:

  db:
    image: mysql:8.0
    container_name: presentia_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: presentia
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: presentia_pma
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"

  web:
    build: .
    container_name: presentia_app
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  db_data: